services:
  backend-grade-service:
    build:
      context: .
      dockerfile: src/Dockerfile
    container_name: backend-grade-service
    depends_on:
      mongodb-grade-service:
        condition: service_healthy
    ports:
      - "5001:5001"
    networks:
      - backend-grade-service
      - gateway-network   # ðŸ”¹ Se conecta al gateway

  mongodb-grade-service:
    image: mongo:6
    container_name: mongodb-grade-service
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: 123
      MONGO_INITDB_DATABASE: grades
    volumes:
      - mongodb-grade-service-data:/data/db
      - ./MongoDB/init.js:/docker-entrypoint-initdb.d/init.js:ro
    ports:
      - "27017:27017"
    networks:
      - backend-grade-service
      - gateway-network
    healthcheck:
      test: ["CMD-SHELL", "mongosh localhost:27017/admin -u admin -p 123 --eval 'db.runCommand({ ping: 1 })'"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  backend-grade-service:
    driver: bridge
  gateway-network:
    external: true    

volumes:
  mongodb-grade-service-data:
    driver: local
